import Head from "next/head";
import { useRouter } from "next/router";
import React, { useState } from "react";
import { Button, Image } from "react-bootstrap";
import { useSelector } from "react-redux";
import AddContact from "./Addtocard";
import ContactCard from "./Contactcard";
import Navbars from "./Navbar";
import { AiOutlinePlus } from "react-icons/ai";

export default function Dashboard() {
  const router = useRouter();
  const handleClick = () => {
    router.push("/product");
  };

  const contacts = useSelector((state) => state.contacts.list);

  const [contactFormVisiblity, setContactFormVisiblity] = useState(false);

  const toggleContactFormVisiblity = () =>
    setContactFormVisiblity((visiblity) => !visiblity);

  return (
    <div>
      <Head>
        <title>Create Apurv App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <>
          <Navbars />
        </>
        <div className="row">
          <div className="col text-center">
            <h2>Manage contacts!!!</h2>

            <div className="col-sm-6 offset-sm-3">
              <div className="card">
                <div
                  className="card-header bg-dark text-white text-left"
                  style={{ display: "flex", justifyContent: "space-between" }}
                >
                  <h4 className="d-inline">Contact List</h4>
                  <span
                    className="float-right mt-1 cursor-pointer"
                    onClick={toggleContactFormVisiblity}
                  >
                    <AiOutlinePlus />
                  </span>
                </div>

                <ul className="list-group list-group-flush">
                  {contacts.map((contact, index) => (
                    <ContactCard
                      {...contact}
                      index={index}
                      key={contact.name}
                    />
                  ))}
                </ul>
              </div>
            </div>
            {contactFormVisiblity && (
              <AddContact onClose={toggleContactFormVisiblity} />
            )}
          </div>
        </div>
        <div style={{margin :"10px" , textAlignLast :"center"}}>
        <Button onClick={handleClick} >Place order</Button>
        </div>
      </div>

      <footer style={{margin : "10px" , textAlignLast :"center"}}> 
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
